# Generated by Django 5.0.8 on 2024-08-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='reting',
            new_name='rating',
        ),
    ]
