# Generated by Django 5.0.8 on 2024-08-15 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_rename_reting_reviews_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='books',
            new_name='book',
        ),
    ]
