# Generated by Django 5.0.8 on 2024-09-04 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Fine', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='borrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.borrow'),
        ),
        migrations.AddField(
            model_name='fine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='fine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Fine.fine'),
        ),
    ]
